name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: docker build -t $DOCKER_REGISTRY/nodejs:latest .
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    - name: docker push
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/nodejs:latest
    - name: Updating tag in docker-compose.yaml file
      run: |
        export GITHUB_USER=saikrishna-snp
        export GITHUB_TOKEN=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
        export VERSION_TAG=$GITHUB_SHA
        git config --global user.email "saikrishna.g@snp.com"
        git config --global user.name $GITHUB_USER
        git clone https://github.com/$GITHUB_USER/docker-compose.git
        git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/docker-compose.git
        sed -i "s/nodeapp/nodeapp:$VERSION_TAG/" docker-compose/docker-compose.yml
        cat docker-compose/docker-compose.yml
        git add .
        git commit -m "Updating node application latest image tag in docker-compose.yml file"
        git push origin
        
