name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_REGISTRY/nodejs:latest
      env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    - name: docker push latest
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/nodejs:latest
