name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: docker build -t $DOCKER_REGISTRY/nodejs:latest .
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    - name: docker push
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/nodejs:latest
  deploy:
    needs: [build]
    runs-on: self-hosted
    
    steps:
    - name: docker version
      run: |
       docker version
       cd /home/ubuntu/
       docker-compose up -d
        
