name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: docker build -t $DOCKER_REGISTRY/nodejs:latest .
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    - name: docker push
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/nodejs:latest
    - name: Updating tag in docker-compose.yaml file
      run: |
        export GITHUB_USER=saikrishna-snp
        export GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}
        export VERSION_TAG=$GITHUB_SHA        
        git clone https://github.com/$GITHUB_USER/docker-compose.git
        git init
        git config --global user.email "saikrishna.g@snp.com"
        git config --global user.name $GITHUB_USER        
        sed -i "s/nodeapp/nodeapp:$VERSION_TAG/" docker-compose/docker-compose.yml
        cat docker-compose/docker-compose.yml
        git add .
        git commit -m "Updating node application latest image tag in docker-compose.yml file"
        git branch -M main
        git remote set-url origin https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/docker-compose.git
        git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
        git push --force --quiet "https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/docker-compose.git" main:main
